// scripts/generate-sample-import.ts
// Script to generate sample Excel file for player import testing

import * as XLSX from "xlsx";
import * as fs from "fs";
import * as path from "path";

// Helper function to generate a player with all required fields
function generatePlayer(
  id: number,
  firstName: string,
  lastName: string,
  dob: string,
  gender: "M" | "F",
  jersey: string,
  grade: string,
  school: string,
  shirtSize: string,
  position: string,
  experience: string,
  allergies: string,
  teamName: string,
  hasParent2: boolean = false
) {
  const lastNames = [
    "Johnson", "Smith", "Williams", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson",
    "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark",
    "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "King", "Wright", "Lopez",
    "Hill", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez",
    "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans", "Edwards", "Collins", "Stewart", "Sanchez"
  ];
  
  const parentLastName = lastNames[id % lastNames.length] || lastName;
  const parent1FirstName = gender === "M" ? "John" : "Mary";
  const parent2FirstName = gender === "M" ? "Jane" : "Robert";
  
  return {
    player_external_id: `EXT${String(id).padStart(3, "0")}`,
    player_first_name: firstName,
    player_last_name: lastName,
    player_dob: dob,
    player_gender: gender,
    jersey_number: jersey,
    grade: grade,
    school_name: school,
    shirt_size: shirtSize,
    position_preference: position,
    previous_experience: experience,
    medical_allergies: allergies,
    medical_conditions: "",
    medical_medications: "",
    doctor_name: allergies ? "Dr. Smith" : "",
    doctor_phone: allergies ? "555-9999" : "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: teamName,
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: parent1FirstName,
    parent1_last_name: parentLastName,
    parent1_phone: `555-${String(id).padStart(4, "0")}`,
    parent1_relationship: gender === "M" ? "Father" : "Mother",
    parent1_address_line1: `${100 + id} ${["Main", "Oak", "Elm", "Maple", "Cedar", "Pine", "Birch", "Spruce", "Willow", "Cherry"][id % 10]} ${["St", "Ave", "Dr", "Ln", "Way", "Blvd"][Math.floor(id / 10) % 6]}`,
    parent1_address_line2: id % 3 === 0 ? `Apt ${id % 20}` : "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: `627${String(id % 100).padStart(2, "0")}`,
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: hasParent2 ? `parent2.${parentLastName.toLowerCase()}@example.com` : "",
    parent2_first_name: hasParent2 ? parent2FirstName : "",
    parent2_last_name: hasParent2 ? parentLastName : "",
    parent2_phone: hasParent2 ? `555-${String(id + 1000).padStart(4, "0")}` : "",
    parent2_relationship: hasParent2 ? (gender === "M" ? "Mother" : "Father") : "",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  };
}

// Sample data for 50 players
// Using actual team names from the database
const teams = [
  "WCS Eagles Elite",
  "WCS Falcons",
  "WCS Lightning",
  "WCS Dupy",
  "WCS Blue",
  "WCS Thunder",
  "WCS Warriors",
  "WCS Sharks",
  "WCS Potter",
  "WCS Red",
  "WCS Swish",
  "WCS Vipers",
  "WCS Williams",
  "WCS Legends",
];

const firstNames = {
  M: ["Michael", "James", "William", "Benjamin", "Lucas", "Henry", "Alexander", "Daniel", "Matthew", "David", "Joseph", "Christopher", "Andrew", "Joshua", "Ryan", "Nicholas", "Tyler", "Jacob", "Brandon", "Nathan", "Jonathan", "Ethan", "Samuel", "Noah", "Caleb"],
  F: ["Emma", "Olivia", "Sophia", "Isabella", "Ava", "Mia", "Charlotte", "Amelia", "Harper", "Evelyn", "Abigail", "Emily", "Elizabeth", "Sofia", "Avery", "Ella", "Madison", "Scarlett", "Victoria", "Aria", "Grace", "Chloe", "Lily", "Natalie", "Zoey"]
};

const grades = ["3rd", "4th", "5th", "6th", "7th", "8th"];
const schools = [
  "Lincoln Elementary", "Washington Elementary", "Roosevelt Elementary", "Jefferson Elementary",
  "Madison Elementary", "Adams Elementary", "Monroe Elementary", "Jackson Elementary",
  "Harrison Elementary", "Tyler Elementary", "Polk Elementary", "Fillmore Elementary"
];
const shirtSizes = ["Youth Small", "Youth Medium", "Youth Large", "Adult Small"];
const positions = ["Guard", "Forward", "Center"];
const experiences = ["1", "2", "3", "4", "5"];

const samplePlayers = [
  {
    player_external_id: "EXT001",
    player_first_name: "Emma",
    player_last_name: "Johnson",
    player_dob: "2010-05-15",
    player_gender: "F",
    jersey_number: "5",
    grade: "5th",
    school_name: "Lincoln Elementary",
    shirt_size: "Youth Medium",
    position_preference: "Guard",
    previous_experience: "3",
    medical_allergies: "Peanuts",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "Dr. Smith",
    doctor_phone: "555-9999",
    emergency_contact: "Grandma Johnson",
    emergency_phone: "555-9998",
    team_name: "WCS Eagles Elite",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Johnson",
    parent1_phone: "555-0101",
    parent1_relationship: "Father",
    parent1_address_line1: "123 Main St",
    parent1_address_line2: "Apt 4B",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62701",
    parent1_emergency_contact: "Grandma Johnson",
    parent1_emergency_phone: "555-9998",
    parent2_email: "jane.johnson@example.com",
    parent2_first_name: "Jane",
    parent2_last_name: "Johnson",
    parent2_phone: "555-0102",
    parent2_relationship: "Mother",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT002",
    player_first_name: "Michael",
    player_last_name: "Smith",
    player_dob: "2011-08-22",
    player_gender: "M",
    jersey_number: "12",
    grade: "4th",
    school_name: "Washington Elementary",
    shirt_size: "Youth Small",
    position_preference: "Forward",
    previous_experience: "2",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Falcons",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Smith",
    parent1_phone: "555-0201",
    parent1_relationship: "Father",
    parent1_address_line1: "456 Oak Ave",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62702",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "",
    parent2_first_name: "",
    parent2_last_name: "",
    parent2_phone: "",
    parent2_relationship: "",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT003",
    player_first_name: "Olivia",
    player_last_name: "Williams",
    player_dob: "2010-11-03",
    player_gender: "F",
    jersey_number: "8",
    grade: "5th",
    school_name: "Roosevelt Elementary",
    shirt_size: "Youth Medium",
    position_preference: "Center",
    previous_experience: "4",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Dupy",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Williams",
    parent1_phone: "555-0301",
    parent1_relationship: "Guardian",
    parent1_address_line1: "789 Elm St",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62703",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "",
    parent2_first_name: "",
    parent2_last_name: "",
    parent2_phone: "",
    parent2_relationship: "",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT004",
    player_first_name: "James",
    player_last_name: "Brown",
    player_dob: "2011-02-14",
    player_gender: "M",
    jersey_number: "23",
    grade: "4th",
    school_name: "Jefferson Elementary",
    shirt_size: "Youth Small",
    position_preference: "Center",
    previous_experience: "1",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Lightning",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Brown",
    parent1_phone: "555-0401",
    parent1_relationship: "Father",
    parent1_address_line1: "321 Pine St",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62704",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "mary.brown@example.com",
    parent2_first_name: "Mary",
    parent2_last_name: "Brown",
    parent2_phone: "555-0402",
    parent2_relationship: "Mother",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT005",
    player_first_name: "Sophia",
    player_last_name: "Davis",
    player_dob: "2010-09-07",
    player_gender: "F",
    jersey_number: "10",
    grade: "5th",
    school_name: "Madison Elementary",
    shirt_size: "Youth Medium",
    position_preference: "Guard",
    previous_experience: "3",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Eagles Elite",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Davis",
    parent1_phone: "555-0501",
    parent1_relationship: "Father",
    parent1_address_line1: "654 Maple Ave",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62705",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "",
    parent2_first_name: "",
    parent2_last_name: "",
    parent2_phone: "",
    parent2_relationship: "",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT006",
    player_first_name: "William",
    player_last_name: "Miller",
    player_dob: "2011-04-18",
    player_gender: "M",
    jersey_number: "7",
    grade: "4th",
    school_name: "Adams Elementary",
    shirt_size: "Youth Small",
    position_preference: "Forward",
    previous_experience: "2",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Falcons",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Miller",
    parent1_phone: "555-0601",
    parent1_relationship: "Father",
    parent1_address_line1: "987 Cedar St",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62706",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "sarah.miller@example.com",
    parent2_first_name: "Sarah",
    parent2_last_name: "Miller",
    parent2_phone: "555-0602",
    parent2_relationship: "Mother",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT007",
    player_first_name: "Isabella",
    player_last_name: "Wilson",
    player_dob: "2010-12-25",
    player_gender: "F",
    jersey_number: "15",
    grade: "5th",
    school_name: "Monroe Elementary",
    shirt_size: "Youth Medium",
    position_preference: "Center",
    previous_experience: "4",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Dupy",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Wilson",
    parent1_phone: "555-0701",
    parent1_relationship: "Father",
    parent1_address_line1: "147 Birch Ln",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62707",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "",
    parent2_first_name: "",
    parent2_last_name: "",
    parent2_phone: "",
    parent2_relationship: "",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT008",
    player_first_name: "Benjamin",
    player_last_name: "Moore",
    player_dob: "2011-06-30",
    player_gender: "M",
    jersey_number: "4",
    grade: "4th",
    school_name: "Jackson Elementary",
    shirt_size: "Youth Small",
    position_preference: "Guard",
    previous_experience: "3",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Lightning",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Moore",
    parent1_phone: "555-0801",
    parent1_relationship: "Father",
    parent1_address_line1: "258 Spruce Dr",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62708",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "lisa.moore@example.com",
    parent2_first_name: "Lisa",
    parent2_last_name: "Moore",
    parent2_phone: "555-0802",
    parent2_relationship: "Mother",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT009",
    player_first_name: "Ava",
    player_last_name: "Taylor",
    player_dob: "2010-07-12",
    player_gender: "F",
    jersey_number: "9",
    grade: "5th",
    school_name: "Harrison Elementary",
    shirt_size: "Youth Medium",
    position_preference: "Forward",
    previous_experience: "2",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Eagles Elite",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Taylor",
    parent1_phone: "555-0901",
    parent1_relationship: "Father",
    parent1_address_line1: "369 Willow Way",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62709",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "",
    parent2_first_name: "",
    parent2_last_name: "",
    parent2_phone: "",
    parent2_relationship: "",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  {
    player_external_id: "EXT010",
    player_first_name: "Lucas",
    player_last_name: "Anderson",
    player_dob: "2011-01-28",
    player_gender: "M",
    jersey_number: "11",
    grade: "4th",
    school_name: "Tyler Elementary",
    shirt_size: "Youth Small",
    position_preference: "Guard",
    previous_experience: "3",
    medical_allergies: "",
    medical_conditions: "",
    medical_medications: "",
    doctor_name: "",
    doctor_phone: "",
    emergency_contact: "",
    emergency_phone: "",
    team_name: "WCS Falcons",
    season: "2025-2026",
    parent1_email: "phronesis700@gmail.com",
    parent1_first_name: "John",
    parent1_last_name: "Anderson",
    parent1_phone: "555-1001",
    parent1_relationship: "Father",
    parent1_address_line1: "741 Cherry Blvd",
    parent1_address_line2: "",
    parent1_city: "Springfield",
    parent1_state: "IL",
    parent1_zip: "62710",
    parent1_emergency_contact: "",
    parent1_emergency_phone: "",
    parent2_email: "karen.anderson@example.com",
    parent2_first_name: "Karen",
    parent2_last_name: "Anderson",
    parent2_phone: "555-1002",
    parent2_relationship: "Mother",
    parent2_address_line1: "",
    parent2_address_line2: "",
    parent2_city: "",
    parent2_state: "",
    parent2_zip: "",
    parent2_emergency_contact: "",
    parent2_emergency_phone: "",
  },
  // Generate 40 more players (11-50)
  ...Array.from({ length: 40 }, (_, i) => {
    const playerNum = i + 11;
    const gender = playerNum % 2 === 0 ? "M" : "F" as "M" | "F";
    const firstName = firstNames[gender][playerNum % firstNames[gender].length];
    const lastName = ["Johnson", "Smith", "Williams", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson",
      "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark",
      "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "King", "Wright", "Lopez",
      "Hill", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez"][playerNum % 40];
    
    // Generate DOB based on grade (approximate ages)
    const gradeNum = parseInt(grades[playerNum % grades.length]) || 5;
    const birthYear = 2025 - gradeNum - 5; // Rough estimate
    const birthMonth = String((playerNum % 12) + 1).padStart(2, "0");
    const birthDay = String((playerNum % 28) + 1).padStart(2, "0");
    const dob = `${birthYear}-${birthMonth}-${birthDay}`;
    
    return generatePlayer(
      playerNum,
      firstName,
      lastName,
      dob,
      gender,
      String((playerNum % 30) + 1),
      grades[playerNum % grades.length],
      schools[playerNum % schools.length],
      shirtSizes[playerNum % shirtSizes.length],
      positions[playerNum % positions.length],
      experiences[playerNum % experiences.length],
      playerNum % 5 === 0 ? (playerNum % 2 === 0 ? "Peanuts" : "Dairy") : "",
      teams[playerNum % teams.length],
      playerNum % 3 === 0 // Every 3rd player has a second parent
    );
  }),
];

// Define headers (matching the template)
const headers = [
  // Player basic info
  "player_external_id",
  "player_first_name",
  "player_last_name",
  "player_dob",
  "player_gender",
  "jersey_number",
  "grade",
  "school_name",
  "shirt_size",
  "position_preference",
  "previous_experience",
  // Player medical info
  "medical_allergies",
  "medical_conditions",
  "medical_medications",
  "doctor_name",
  "doctor_phone",
  "emergency_contact",
  "emergency_phone",
  // Team info
  "team_name",
  "season",
  // Parent 1 info
  "parent1_email",
  "parent1_first_name",
  "parent1_last_name",
  "parent1_phone",
  "parent1_relationship",
  "parent1_address_line1",
  "parent1_address_line2",
  "parent1_city",
  "parent1_state",
  "parent1_zip",
  "parent1_emergency_contact",
  "parent1_emergency_phone",
  // Parent 2 info (all optional)
  "parent2_email",
  "parent2_first_name",
  "parent2_last_name",
  "parent2_phone",
  "parent2_relationship",
  "parent2_address_line1",
  "parent2_address_line2",
  "parent2_city",
  "parent2_state",
  "parent2_zip",
  "parent2_emergency_contact",
  "parent2_emergency_phone",
];

// Convert data to array of arrays
const rows = samplePlayers.map((player) => [
  player.player_external_id,
  player.player_first_name,
  player.player_last_name,
  player.player_dob,
  player.player_gender,
  player.jersey_number,
  player.grade || "",
  player.school_name || "",
  player.shirt_size || "",
  player.position_preference || "",
  player.previous_experience || "",
  player.medical_allergies || "",
  player.medical_conditions || "",
  player.medical_medications || "",
  player.doctor_name || "",
  player.doctor_phone || "",
  player.emergency_contact || "",
  player.emergency_phone || "",
  player.team_name,
  player.season,
  player.parent1_email,
  player.parent1_first_name,
  player.parent1_last_name,
  player.parent1_phone,
  player.parent1_relationship,
  player.parent1_address_line1 || "",
  player.parent1_address_line2 || "",
  player.parent1_city || "",
  player.parent1_state || "",
  player.parent1_zip || "",
  player.parent1_emergency_contact || "",
  player.parent1_emergency_phone || "",
  player.parent2_email || "",
  player.parent2_first_name || "",
  player.parent2_last_name || "",
  player.parent2_phone || "",
  player.parent2_relationship || "",
  player.parent2_address_line1 || "",
  player.parent2_address_line2 || "",
  player.parent2_city || "",
  player.parent2_state || "",
  player.parent2_zip || "",
  player.parent2_emergency_contact || "",
  player.parent2_emergency_phone || "",
]);

// Create workbook
const workbook = XLSX.utils.book_new();
const worksheetData = [headers, ...rows];
const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

// Set column widths (matching the template)
worksheet["!cols"] = [
  { wch: 18 }, // player_external_id
  { wch: 15 }, // player_first_name
  { wch: 15 }, // player_last_name
  { wch: 12 }, // player_dob
  { wch: 10 }, // player_gender
  { wch: 12 }, // jersey_number
  { wch: 10 }, // grade
  { wch: 20 }, // school_name
  { wch: 15 }, // shirt_size
  { wch: 15 }, // position_preference
  { wch: 18 }, // previous_experience
  { wch: 20 }, // medical_allergies
  { wch: 20 }, // medical_conditions
  { wch: 20 }, // medical_medications
  { wch: 15 }, // doctor_name
  { wch: 15 }, // doctor_phone
  { wch: 18 }, // emergency_contact
  { wch: 15 }, // emergency_phone
  { wch: 20 }, // team_name
  { wch: 15 }, // season
  { wch: 25 }, // parent1_email
  { wch: 15 }, // parent1_first_name
  { wch: 15 }, // parent1_last_name
  { wch: 15 }, // parent1_phone
  { wch: 18 }, // parent1_relationship
  { wch: 20 }, // parent1_address_line1
  { wch: 15 }, // parent1_address_line2
  { wch: 15 }, // parent1_city
  { wch: 10 }, // parent1_state
  { wch: 10 }, // parent1_zip
  { wch: 20 }, // parent1_emergency_contact
  { wch: 15 }, // parent1_emergency_phone
  { wch: 25 }, // parent2_email
  { wch: 15 }, // parent2_first_name
  { wch: 15 }, // parent2_last_name
  { wch: 15 }, // parent2_phone
  { wch: 18 }, // parent2_relationship
  { wch: 20 }, // parent2_address_line1
  { wch: 15 }, // parent2_address_line2
  { wch: 15 }, // parent2_city
  { wch: 10 }, // parent2_state
  { wch: 10 }, // parent2_zip
  { wch: 20 }, // parent2_emergency_contact
  { wch: 15 }, // parent2_emergency_phone
];

// Add worksheet to workbook
XLSX.utils.book_append_sheet(workbook, worksheet, "Players");

// Generate Excel file buffer
const excelBuffer = XLSX.write(workbook, {
  type: "buffer",
  bookType: "xlsx",
});

// Save to docs directory
const outputPath = path.join(process.cwd(), "docs", "sample-player-import.xlsx");
fs.writeFileSync(outputPath, excelBuffer);

console.log(`✅ Sample import file created: ${outputPath}`);
console.log(`📊 Contains ${samplePlayers.length} players`);
console.log(`📧 All players use parent email: phronesis700@gmail.com`);
console.log(`🏀 Teams included: ${[...new Set(samplePlayers.map(p => p.team_name))].join(", ")}`);

